import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { addDoc, collection, deleteDoc, doc, getDocs, runTransaction, updateDoc, query, orderBy, serverTimestamp } from 'firebase/firestore';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { db, auth, configured } from './firebase';
import { ArrowDownRight, ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, Check, CheckCircle2, ChevronDown, CircleHelp, ClipboardList, Download, Fingerprint, KeyRound, LayoutDashboard, LockKeyhole, LogOut, Mail, MapPin, Menu, Pencil, Phone, Plus, Search, ShieldCheck, Sparkles, Trash2, UserRound, Users, X } from 'lucide-react';
import './styles.css';

const departments = ['Engineering','Product & Design','Data & Analytics','Human Resources','Finance & Accounts','Marketing','Sales & Business Development','Operations','Customer Success','Legal & Compliance','Other'];
const roles = ['Intern','Associate','Executive','Senior Executive','Team Lead','Manager','Senior Manager','Director','Other'];
const initialForm = { firstName:'', lastName:'', email:'', phone:'', department:'', designation:'', employmentType:'', joiningDate:'', location:'', address:'', emergencyName:'', emergencyPhone:'' };
const ADMIN_EMAIL = 'subhra02.biswas@gmail.com'; // Change this to your administrator email; also update firestore.rules.
const employeeCode = () => `NX-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;
const clean = s => String(s || '').trim();
const initials = e => `${e.firstName?.[0] || ''}${e.lastName?.[0] || ''}`.toUpperCase();

function App(){
  const [page,setPage] = useState('home');
  const [form,setForm] = useState(initialForm);
  const [errors,setErrors] = useState({});
  const [saved,setSaved] = useState(null);
  const [busy,setBusy] = useState(false);
  const [toast,setToast] = useState('');
  const [user,setUser] = useState(null);
  const [employees,setEmployees] = useState([]);
  const [loading,setLoading] = useState(false);
  const [search,setSearch] = useState('');
  const [deptFilter,setDeptFilter] = useState('All departments');
  const [editItem,setEditItem] = useState(null);
  const [login,setLogin] = useState({email:'',password:''});
  const [loginError,setLoginError] = useState('');
  const [mobileMenu,setMobileMenu] = useState(false);
  const [confirmDelete,setConfirmDelete] = useState(null);

  useEffect(()=>{ if(!configured) return; return onAuthStateChanged(auth, u=>setUser(u)); },[]);
  useEffect(()=>{ if(page==='admin' && user) loadEmployees(); },[page,user]);
  useEffect(()=>{ if(toast){const t=setTimeout(()=>setToast(''),3600);return ()=>clearTimeout(t)} },[toast]);
  const update = (key,value) => { setForm(p=>({...p,[key]:value})); setErrors(p=>({...p,[key]:''})); };
  const validate = (data=form) => {
    const e={};
    ['firstName','lastName','email','phone','department','designation','employmentType','joiningDate','location'].forEach(k=>{if(!clean(data[k]))e[k]='This field is required.'});
    if(data.email && !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(data.email))e.email='Enter a valid email address.';
    if(data.phone && !/^[6-9]\d{9}$/.test(data.phone))e.phone='Enter a valid 10-digit Indian mobile number.';
    if(data.emergencyPhone && !/^[6-9]\d{9}$/.test(data.emergencyPhone))e.emergencyPhone='Enter a valid 10-digit mobile number.';
    return e;
  };
  const submit = async ev => {
    ev.preventDefault(); const e=validate(); setErrors(e); if(Object.keys(e).length)return;
    if(!configured){setToast('Connect your Firebase project first — see SETUP.md.');return;}
    setBusy(true);
    try{
      const emailKey=clean(form.email).toLowerCase(); const phoneKey=clean(form.phone);
      const code=employeeCode(); const ref=doc(collection(db,'employees'));
      await runTransaction(db,async tx=>{
        const emailRef=doc(db,'uniqueEmails',encodeURIComponent(emailKey));
        const phoneRef=doc(db,'uniquePhones',phoneKey);
        const [emailSnap,phoneSnap]=await Promise.all([tx.get(emailRef),tx.get(phoneRef)]);
        if(emailSnap.exists()) throw new Error('This email is already registered.');
        if(phoneSnap.exists()) throw new Error('This phone number is already registered.');
        const record={...form, email:emailKey, employeeId:code, createdAt:serverTimestamp(), updatedAt:serverTimestamp()};
        tx.set(ref,record); tx.set(emailRef,{employeeDoc:ref.id}); tx.set(phoneRef,{employeeDoc:ref.id});
      });
      setSaved({ ...form, employeeId:code }); setForm(initialForm); window.scrollTo({top:0,behavior:'smooth'});
    }catch(err){setToast(err.message || 'Could not submit the form. Please try again.');}
    finally{setBusy(false)}
  };
  const loadEmployees = async()=>{ if(!configured)return; setLoading(true); try{const snap=await getDocs(query(collection(db,'employees'),orderBy('createdAt','desc')));setEmployees(snap.docs.map(d=>({id:d.id,...d.data()})));}catch(e){setToast('Could not load employees. Check Firestore rules and admin access.');}finally{setLoading(false)} };
  const loginAdmin=async ev=>{ev.preventDefault();setLoginError('');if(!configured){setLoginError('Add Firebase settings in src/firebase.js first.');return;}try{const cred=await signInWithEmailAndPassword(auth,login.email,login.password);if(cred.user.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){await signOut(auth);setLoginError('This account is not configured as the administrator.');return;}setPage('admin');}catch(e){setLoginError('Sign-in failed. Check your email and password.');}};
  const saveEdit=async ev=>{ev.preventDefault();const e=validate(editItem);if(Object.keys(e).length){setToast('Please check required fields and formats.');return;}try{const old=employees.find(x=>x.id===editItem.id);const oldEmail=old.email.toLowerCase(),newEmail=editItem.email.trim().toLowerCase(),oldPhone=old.phone,newPhone=editItem.phone.trim();await runTransaction(db,async tx=>{const oldEmailRef=doc(db,'uniqueEmails',encodeURIComponent(oldEmail)),newEmailRef=doc(db,'uniqueEmails',encodeURIComponent(newEmail)),oldPhoneRef=doc(db,'uniquePhones',oldPhone),newPhoneRef=doc(db,'uniquePhones',newPhone);const refs=[oldEmailRef,newEmailRef,oldPhoneRef,newPhoneRef];const snaps=await Promise.all(refs.map(r=>tx.get(r)));if(newEmail!==oldEmail&&snaps[1].exists()&&snaps[1].data().employeeDoc!==editItem.id)throw new Error('That email is already assigned to another employee.');if(newPhone!==oldPhone&&snaps[3].exists()&&snaps[3].data().employeeDoc!==editItem.id)throw new Error('That phone number is already assigned to another employee.');tx.update(doc(db,'employees',editItem.id),{...editItem,email:newEmail,phone:newPhone,updatedAt:serverTimestamp()});if(newEmail!==oldEmail){tx.delete(oldEmailRef);tx.set(newEmailRef,{employeeDoc:editItem.id});}if(newPhone!==oldPhone){tx.delete(oldPhoneRef);tx.set(newPhoneRef,{employeeDoc:editItem.id});}});setEditItem(null);setToast('Employee record updated.');loadEmployees();}catch(e){setToast(e.message||'Update failed. Check Firestore rules.');}};
  const removeEmployee=async item=>{try{await deleteDoc(doc(db,'employees',item.id));await deleteDoc(doc(db,'uniqueEmails',encodeURIComponent(item.email.toLowerCase())));await deleteDoc(doc(db,'uniquePhones',item.phone));setConfirmDelete(null);setToast('Employee record deleted.');loadEmployees();}catch(e){setToast('Delete failed. Check Firestore rules.');}};
  const filtered=useMemo(()=>employees.filter(e=>`${e.firstName} ${e.lastName} ${e.employeeId} ${e.email} ${e.department}`.toLowerCase().includes(search.toLowerCase())&&(deptFilter==='All departments'||e.department===deptFilter)),[employees,search,deptFilter]);
  const exportCSV=()=>{const keys=['employeeId','firstName','lastName','email','phone','department','designation','employmentType','joiningDate','location'];const csv=[keys.join(','),...filtered.map(e=>keys.map(k=>`"${String(e[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='nexa-employee-directory.csv';a.click();URL.revokeObjectURL(a.href);};
  const nav=(p)=>{setPage(p);setMobileMenu(false);setSaved(null);window.scrollTo({top:0,behavior:'smooth'});};

  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>nav('home')}><span className="brand-mark"><Fingerprint size={22}/></span><span>NEXA<span className="brand-light">/PEOPLE</span><small>PEOPLE OPERATIONS</small></span></button><nav className={mobileMenu?'nav-links open':'nav-links'}><button className={page==='home'?'nav-item active':'nav-item'} onClick={()=>nav('home')}>New registration</button><button className={page==='admin'?'nav-item active':'nav-item'} onClick={()=>nav(user?'admin':'login')}>Admin workspace <ArrowDownRight size={14}/></button></nav><button className="nav-cta" onClick={()=>nav(user?'admin':'login')}><LockKeyhole size={15}/> Admin access</button><button className="menu-toggle" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button></header>
    <main>
      {page==='home' && <>
        <section className="hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-content"><div className="eyebrow"><span className="eyebrow-line"/> PEOPLE. PROCESS. POSSIBILITY.</div><h1>Every great team<br/>starts with <em>you.</em></h1><p className="hero-copy">A thoughtful first step into your next chapter. Complete your employee profile and let’s get the essentials in place.</p><div className="hero-meta"><span><ShieldCheck size={16}/> Secure employee onboarding</span><span className="meta-dot"/><span>02—05 MIN</span></div></div><div className="hero-side-note"><span className="side-number">01</span><span className="side-rule"/><span>EMPLOYEE<br/>ONBOARDING</span></div><div className="hero-bottom"><span>BUILT AROUND PEOPLE</span><span>SCROLL TO BEGIN <ArrowRight size={14}/></span></div></section>
        {saved ? <section className="success-wrap"><div className="success-card"><div className="success-icon"><CheckCircle2 size={30}/></div><div className="eyebrow">REGISTRATION COMPLETE</div><h2>You’re on the list.</h2><p>Your employee profile has been securely submitted. Keep your unique employee ID handy for future reference.</p><div className="id-ticket"><span>YOUR EMPLOYEE ID</span><strong>{saved.employeeId}</strong><button onClick={()=>navigator.clipboard?.writeText(saved.employeeId)} title="Copy ID"><ClipboardList size={17}/></button></div><button className="button-primary" onClick={()=>setSaved(null)}>Register another employee <ArrowRight size={17}/></button></div></section> : <section className="form-section" id="registration"><div className="section-intro"><div className="eyebrow dark"><span className="eyebrow-line"/> LET’S GET STARTED</div><h2>Make it <em>official.</em></h2><p>Share a few details to create your employee profile. Fields marked with <b>*</b> are required.</p><div className="form-progress"><span>YOUR PROFILE</span><div><span/></div><span>01 / 03</span></div></div>
          <form className="employee-form" onSubmit={submit} noValidate><div className="form-heading"><div><span className="form-step">01</span><h3>Personal details</h3><p>First, the basics that help us know you.</p></div><UserRound size={21}/></div><div className="fields-grid"><Field label="First name" required value={form.firstName} onChange={v=>update('firstName',v)} error={errors.firstName} placeholder="e.g. Aanya"/><Field label="Last name" required value={form.lastName} onChange={v=>update('lastName',v)} error={errors.lastName} placeholder="e.g. Sharma"/><Field label="Work email address" required value={form.email} onChange={v=>update('email',v)} error={errors.email} placeholder="name@company.com" type="email" icon={<Mail size={16}/>}/><Field label="Mobile number" required value={form.phone} onChange={v=>update('phone',v.replace(/\D/g,'').slice(0,10))} error={errors.phone} placeholder="10-digit mobile number" type="tel" icon={<Phone size={16}/>} maxLength={10}/></div>
            <div className="form-heading second"><div><span className="form-step">02</span><h3>Role & workplace</h3><p>Tell us where you’ll make an impact.</p></div><BriefcaseBusiness size={21}/></div><div className="fields-grid"><SelectField label="Department" required value={form.department} onChange={v=>update('department',v)} error={errors.department} options={departments} placeholder="Choose a department"/><Field label="Job title / designation" required value={form.designation} onChange={v=>update('designation',v)} error={errors.designation} placeholder="e.g. Software Engineer"/><SelectField label="Employment type" required value={form.employmentType} onChange={v=>update('employmentType',v)} error={errors.employmentType} options={['Full-time','Part-time','Internship','Contract','Freelance']} placeholder="Choose employment type"/><Field label="Date of joining" required value={form.joiningDate} onChange={v=>update('joiningDate',v)} error={errors.joiningDate} type="date"/><Field label="Office location" required value={form.location} onChange={v=>update('location',v)} error={errors.location} placeholder="e.g. Hyderabad / Remote" icon={<MapPin size={16}/>} wide/><Field label="Current address" value={form.address} onChange={v=>update('address',v)} placeholder="Street, city, state, PIN" wide/></div>
            <div className="form-heading second"><div><span className="form-step">03</span><h3>Emergency contact <span className="optional">OPTIONAL</span></h3><p>Someone we can reach out to if needed.</p></div><CircleHelp size={21}/></div><div className="fields-grid"><Field label="Contact person’s name" value={form.emergencyName} onChange={v=>update('emergencyName',v)} placeholder="Full name"/><Field label="Contact phone number" value={form.emergencyPhone} onChange={v=>update('emergencyPhone',v.replace(/\D/g,'').slice(0,10))} error={errors.emergencyPhone} placeholder="10-digit mobile number" type="tel" maxLength={10}/></div>
            <div className="form-footer"><div className="privacy-note"><LockKeyhole size={16}/><span>Your information is used only for employee administration and is accessible to authorized personnel.</span></div><button className="button-primary submit-button" type="submit" disabled={busy}>{busy?'Submitting…':'Submit employee profile'} {busy?<span className="spinner"/>:<ArrowRight size={17}/>}</button></div>
          </form></section>}
        <section className="bottom-strip"><div><span className="strip-icon"><BadgeCheck size={19}/></span><div><strong>Made for a smooth start.</strong><p>Simple, secure, and thoughtfully organized.</p></div></div><span className="strip-right">NEXA / PEOPLE <span>© 2026</span></span></section>
      </>}
      {page==='login' && <section className="admin-auth"><div className="auth-decoration"><div className="eyebrow"><span className="eyebrow-line"/> RESTRICTED ACCESS</div><h1>People ops,<br/><em>in control.</em></h1><p>A dedicated workspace for authorized administrators to manage employee records.</p><div className="auth-ornament"><Building2 size={68} strokeWidth={0.8}/><span>CONFIDENTIAL · INTERNAL USE</span></div></div><form className="login-card" onSubmit={loginAdmin}><div className="login-symbol"><KeyRound size={22}/></div><div className="eyebrow dark">ADMINISTRATOR SIGN IN</div><h2>Welcome back.</h2><p>Sign in with your authorized administrator account.</p><label className="field-label">Admin email <span>*</span></label><div className="input-wrap"><Mail size={16}/><input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} placeholder="admin@company.com"/></div><label className="field-label">Password <span>*</span></label><div className="input-wrap"><LockKeyhole size={16}/><input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="Enter your password"/></div>{loginError&&<div className="inline-error">{loginError}</div>}<button className="button-primary full" type="submit">Sign in to workspace <ArrowRight size={17}/></button><button type="button" className="back-link" onClick={()=>nav('home')}><ArrowLeft size={15}/> Back to registration</button><div className="auth-secure"><ShieldCheck size={15}/> Protected with Firebase Authentication</div></form></section>}
      {page==='admin' && !user && <section className="admin-auth"><div className="auth-decoration"><div className="eyebrow"><span className="eyebrow-line"/> RESTRICTED ACCESS</div><h1>People ops,<br/><em>in control.</em></h1><p>Sign in to access the employee directory and manage records.</p></div><form className="login-card" onSubmit={loginAdmin}><div className="login-symbol"><KeyRound size={22}/></div><div className="eyebrow dark">ADMINISTRATOR SIGN IN</div><h2>Welcome back.</h2><p>Use your authorized administrator account.</p><label className="field-label">Admin email <span>*</span></label><div className="input-wrap"><Mail size={16}/><input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} placeholder="admin@company.com"/></div><label className="field-label">Password <span>*</span></label><div className="input-wrap"><LockKeyhole size={16}/><input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="Enter your password"/></div>{loginError&&<div className="inline-error">{loginError}</div>}<button className="button-primary full" type="submit">Sign in to workspace <ArrowRight size={17}/></button><button type="button" className="back-link" onClick={()=>nav('home')}><ArrowLeft size={15}/> Back to registration</button></form></section>}
      {page==='admin' && user && <section className="dashboard"><div className="dashboard-top"><div><div className="eyebrow dark"><span className="eyebrow-line"/> PEOPLE OPERATIONS</div><h1>Employee <em>directory.</em></h1><p>Manage your people, all in one place.</p></div><button className="button-outline" onClick={async()=>{await signOut(auth);nav('home')}}><LogOut size={16}/> Sign out</button></div><div className="stats-grid"><Stat icon={<Users/>} label="Total employees" value={employees.length}/><Stat icon={<Building2/>} label="Departments" value={new Set(employees.map(e=>e.department)).size}/><Stat icon={<Sparkles/>} label="Added this month" value={employees.filter(e=>e.createdAt?.toDate?.() && e.createdAt.toDate().getMonth()===new Date().getMonth() && e.createdAt.toDate().getFullYear()===new Date().getFullYear()).length}/></div><div className="directory-card"><div className="directory-head"><div><h2>All employees <span>{employees.length}</span></h2><p>View, update, or remove employee records.</p></div><button className="button-outline export" onClick={exportCSV}><Download size={16}/> Export CSV</button></div><div className="directory-tools"><div className="searchbox"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, ID, email…"/></div><select value={deptFilter} onChange={e=>setDeptFilter(e.target.value)}><option>All departments</option>{departments.map(d=><option key={d}>{d}</option>)}</select><button className="icon-button" onClick={loadEmployees} title="Refresh"><ArrowRight size={17}/></button></div>{loading?<div className="empty-state">Loading employee records…</div>:filtered.length===0?<div className="empty-state"><Users size={28}/><strong>No employee records found</strong><span>Try adjusting your search or filters.</span></div>:<div className="table-wrap"><table><thead><tr><th>EMPLOYEE</th><th>EMPLOYEE ID</th><th>DEPARTMENT / ROLE</th><th>CONTACT</th><th>JOINING DATE</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><div className="person-cell"><span className="avatar">{initials(e)}</span><div><strong>{e.firstName} {e.lastName}</strong><small>{e.location}</small></div></div></td><td><span className="employee-code">{e.employeeId}</span></td><td><strong className="dept-name">{e.department}</strong><small className="table-sub">{e.designation}</small></td><td><strong className="contact-email">{e.email}</strong><small className="table-sub">{e.phone}</small></td><td>{e.joiningDate||'—'}</td><td><div className="actions"><button className="action-edit" onClick={()=>setEditItem({...e})} title="Edit"><Pencil size={15}/></button><button className="action-delete" onClick={()=>setConfirmDelete(e)} title="Delete"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}<div className="directory-bottom"><span>Showing {filtered.length} of {employees.length} records</span><span><ShieldCheck size={14}/> Authorized access only</span></div></div></section>}
    </main>
    <footer className="site-footer"><span>© 2026 NEXA / PEOPLE</span><span>PEOPLE FIRST. ALWAYS.</span><button onClick={()=>nav('login')}>ADMIN LOGIN <ArrowRight size={13}/></button></footer>
    {toast&&<div className="toast"><CircleHelp size={17}/>{toast}<button onClick={()=>setToast('')}><X size={15}/></button></div>}
    {editItem&&<div className="modal-backdrop" onClick={()=>setEditItem(null)}><form className="edit-modal" onSubmit={saveEdit} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow dark">EMPLOYEE RECORD</div><h2>Edit employee</h2><p>{editItem.employeeId}</p></div><button type="button" className="icon-button" onClick={()=>setEditItem(null)}><X/></button></div><div className="modal-fields"><Field label="First name" required value={editItem.firstName} onChange={v=>setEditItem({...editItem,firstName:v})}/><Field label="Last name" required value={editItem.lastName} onChange={v=>setEditItem({...editItem,lastName:v})}/><Field label="Email" required value={editItem.email} onChange={v=>setEditItem({...editItem,email:v.toLowerCase()})} type="email"/><Field label="Phone" required value={editItem.phone} onChange={v=>setEditItem({...editItem,phone:v.replace(/\D/g,'').slice(0,10)})}/><SelectField label="Department" required value={editItem.department} onChange={v=>setEditItem({...editItem,department:v})} options={departments}/><Field label="Designation" required value={editItem.designation} onChange={v=>setEditItem({...editItem,designation:v})}/><SelectField label="Employment type" required value={editItem.employmentType} onChange={v=>setEditItem({...editItem,employmentType:v})} options={['Full-time','Part-time','Internship','Contract','Freelance']}/><Field label="Joining date" required value={editItem.joiningDate} onChange={v=>setEditItem({...editItem,joiningDate:v})} type="date"/><Field label="Office location" required value={editItem.location} onChange={v=>setEditItem({...editItem,location:v})} wide/><Field label="Address" value={editItem.address||''} onChange={v=>setEditItem({...editItem,address:v})} wide/></div><div className="modal-actions"><button type="button" className="button-outline" onClick={()=>setEditItem(null)}>Cancel</button><button className="button-primary" type="submit">Save changes <Check size={16}/></button></div></form></div>}
    {confirmDelete&&<div className="modal-backdrop" onClick={()=>setConfirmDelete(null)}><div className="confirm-modal" onClick={e=>e.stopPropagation()}><div className="delete-symbol"><Trash2/></div><h2>Delete this record?</h2><p>This will permanently remove <b>{confirmDelete.firstName} {confirmDelete.lastName}</b> ({confirmDelete.employeeId}) from the employee directory.</p><div className="modal-actions"><button className="button-outline" onClick={()=>setConfirmDelete(null)}>Cancel</button><button className="button-danger" onClick={()=>removeEmployee(confirmDelete)}>Delete employee <Trash2 size={16}/></button></div></div></div>}
  </div>
}
function Field({label,required,value,onChange,error,placeholder,type='text',icon,wide,maxLength}){return <div className={`field ${wide?'wide':''}`}><label className="field-label">{label} {required&&<span>*</span>}</label><div className={`input-wrap ${error?'invalid':''}`}>{icon&&icon}<input type={type} value={value??''} onChange={e=>onChange(e.target.value)} placeholder={placeholder||''} required={required} maxLength={maxLength}/></div>{error&&<small className="field-error">{error}</small>}</div>}
function SelectField({label,required,value,onChange,error,options,placeholder='Select an option'}){return <div className="field"><label className="field-label">{label} {required&&<span>*</span>}</label><div className={`select-wrap ${error?'invalid':''}`}><select value={value||''} onChange={e=>onChange(e.target.value)} required={required}><option value="" disabled>{placeholder}</option>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown size={16}/></div>{error&&<small className="field-error">{error}</small>}</div>}
function Stat({icon,label,value}){return <div className="stat-card"><span className="stat-icon">{icon}</span><div><span>{label}</span><strong>{value}</strong></div><ArrowDownRight className="stat-arrow" size={17}/></div>}

createRoot(document.getElementById('root')).render(<App/>);
